---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alsudais-iam-service
    provider: alsudais
    version: 1.0.0
    group: com.alsudais
  name: alsudais-iam-service
  namespace: alsudais
spec:
  ports:
  - name: sunproxyadmin
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: xmltec-xmlmail
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: alsudais-iam-service
    provider: alsudais
    group: com.alsudais
